name: nakama-node-1
data_dir: "./data/"

logger:
    stdout: true
    level: "warn"
    file: "/nakama/data/logfile.log"

console:
    port: 7351
    username: "Dinginess4282"
    password: "hEyxgVTEf552LSF3f&F8Bw5bn3fLm*jv@b2yK^Ct"